[package]
name = "pilchard"
version = "0.1.0"
authors = ["samipourquoi"]
edition = "2018"

[dependencies]
# lmdb = "0.8.0"
hematite-nbt = "0.5.1"
lazy_static = "1.4.0"
serde = "1.0.124"
serde_json = "1.0.64"
cairo-rs = { version = "0.9.1", features = ["png"] }
force-send-sync = "1.0.0"
